# Generated by Django 5.0.6 on 2024-07-09 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subcategory',
            new_name='parent',
        ),
    ]
