# Generated by Django 5.0.6 on 2024-07-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0002_rename_subcategory_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(blank=True, null=True, related_name='images', to='ecomapp.image'),
        ),
    ]
