# Generated by Django 5.0.6 on 2024-07-09 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomapp.image'),
        ),
    ]
